// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: realtime/v1/realtime.proto

package realtimepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RSVPStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GoingCount      int64                  `protobuf:"varint,1,opt,name=going_count,json=goingCount,proto3" json:"going_count,omitempty"`
	InterestedCount int64                  `protobuf:"varint,2,opt,name=interested_count,json=interestedCount,proto3" json:"interested_count,omitempty"`
	InvitedCount    int64                  `protobuf:"varint,3,opt,name=invited_count,json=invitedCount,proto3" json:"invited_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RSVPStats) Reset() {
	*x = RSVPStats{}
	mi := &file_realtime_v1_realtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSVPStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSVPStats) ProtoMessage() {}

func (x *RSVPStats) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_v1_realtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSVPStats.ProtoReflect.Descriptor instead.
func (*RSVPStats) Descriptor() ([]byte, []int) {
	return file_realtime_v1_realtime_proto_rawDescGZIP(), []int{0}
}

func (x *RSVPStats) GetGoingCount() int64 {
	if x != nil {
		return x.GoingCount
	}
	return 0
}

func (x *RSVPStats) GetInterestedCount() int64 {
	if x != nil {
		return x.InterestedCount
	}
	return 0
}

func (x *RSVPStats) GetInvitedCount() int64 {
	if x != nil {
		return x.InvitedCount
	}
	return 0
}

type ReportRSVPEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Stats         *RSVPStats             `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRSVPEventRequest) Reset() {
	*x = ReportRSVPEventRequest{}
	mi := &file_realtime_v1_realtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRSVPEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRSVPEventRequest) ProtoMessage() {}

func (x *ReportRSVPEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_v1_realtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRSVPEventRequest.ProtoReflect.Descriptor instead.
func (*ReportRSVPEventRequest) Descriptor() ([]byte, []int) {
	return file_realtime_v1_realtime_proto_rawDescGZIP(), []int{1}
}

func (x *ReportRSVPEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ReportRSVPEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReportRSVPEventRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportRSVPEventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ReportRSVPEventRequest) GetStats() *RSVPStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_realtime_v1_realtime_proto protoreflect.FileDescriptor

const file_realtime_v1_realtime_proto_rawDesc = "" +
	"\n" +
	"\x1arealtime/v1/realtime.proto\x12\vrealtime.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"|\n" +
	"\tRSVPStats\x12\x1f\n" +
	"\vgoing_count\x18\x01 \x01(\x03R\n" +
	"goingCount\x12)\n" +
	"\x10interested_count\x18\x02 \x01(\x03R\x0finterestedCount\x12#\n" +
	"\rinvited_count\x18\x03 \x01(\x03R\finvitedCount\"\xcc\x01\n" +
	"\x16ReportRSVPEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12,\n" +
	"\x05stats\x18\x05 \x01(\v2\x16.realtime.v1.RSVPStatsR\x05stats2a\n" +
	"\x0fRealtimeService\x12N\n" +
	"\x0fReportRSVPEvent\x12#.realtime.v1.ReportRSVPEventRequest\x1a\x16.google.protobuf.EmptyB0Z.gitlab.com/spydotech-group/shared-entity/proto/realtime/v1;realtimepbb\x06proto3"

var (
	file_realtime_v1_realtime_proto_rawDescOnce sync.Once
	file_realtime_v1_realtime_proto_rawDescData []byte
)

func file_realtime_v1_realtime_proto_rawDescGZIP() []byte {
	file_realtime_v1_realtime_proto_rawDescOnce.Do(func() {
		file_realtime_v1_realtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realtime_v1_realtime_proto_rawDesc), len(file_realtime_v1_realtime_proto_rawDesc)))
	})
	return file_realtime_v1_realtime_proto_rawDescData
}

var file_realtime_v1_realtime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_realtime_v1_realtime_proto_goTypes = []any{
	(*RSVPStats)(nil),              // 0: realtime.v1.RSVPStats
	(*ReportRSVPEventRequest)(nil), // 1: realtime.v1.ReportRSVPEventRequest
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 3: google.protobuf.Empty
}
var file_realtime_v1_realtime_proto_depIdxs = []int32{
	2, // 0: realtime.v1.ReportRSVPEventRequest.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: realtime.v1.ReportRSVPEventRequest.stats:type_name -> realtime.v1.RSVPStats
	1, // 2: realtime.v1.RealtimeService.ReportRSVPEvent:input_type -> realtime.v1.ReportRSVPEventRequest
	3, // 3: realtime.v1.RealtimeService.ReportRSVPEvent:output_type -> google.protobuf.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_realtime_v1_realtime_proto_init() }
func file_realtime_v1_realtime_proto_init() {
	if File_realtime_v1_realtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realtime_v1_realtime_proto_rawDesc), len(file_realtime_v1_realtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realtime_v1_realtime_proto_goTypes,
		DependencyIndexes: file_realtime_v1_realtime_proto_depIdxs,
		MessageInfos:      file_realtime_v1_realtime_proto_msgTypes,
	}.Build()
	File_realtime_v1_realtime_proto = out.File
	file_realtime_v1_realtime_proto_goTypes = nil
	file_realtime_v1_realtime_proto_depIdxs = nil
}
