{
 "title": "MongoDB Dashboard for Prometheus MongoDB Exporter",
 "description": "MongoDB Dashboard for Prometheus MongoDB Exporter. Works with mongodb_exporter.",
 "tags": [
  "prometheus",
  "mongodb"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(mongodb_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "MongoDB Instance Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mongodb_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap In Use"
    }
   ]
  },
  {
   "title": "Memory Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Allocations"
    },
    {
     "expr": "rate(go_memstats_frees_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Frees"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds_sum{instance=~\"$instance\"}",
     "legendFormat": "GC Time"
    }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_objects{instance=~\"$instance\"}",
     "legendFormat": "Heap Objects"
    }
   ]
  }
 ]
}