// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: events/v1/events.proto

package eventspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventsService_CreateEvent_FullMethodName         = "/events.v1.EventsService/CreateEvent"
	EventsService_GetEvent_FullMethodName            = "/events.v1.EventsService/GetEvent"
	EventsService_UpdateEvent_FullMethodName         = "/events.v1.EventsService/UpdateEvent"
	EventsService_DeleteEvent_FullMethodName         = "/events.v1.EventsService/DeleteEvent"
	EventsService_ListEvents_FullMethodName          = "/events.v1.EventsService/ListEvents"
	EventsService_GetMyEvents_FullMethodName         = "/events.v1.EventsService/GetMyEvents"
	EventsService_RSVP_FullMethodName                = "/events.v1.EventsService/RSVP"
	EventsService_GetBirthdays_FullMethodName        = "/events.v1.EventsService/GetBirthdays"
	EventsService_InviteFriends_FullMethodName       = "/events.v1.EventsService/InviteFriends"
	EventsService_GetInvitations_FullMethodName      = "/events.v1.EventsService/GetInvitations"
	EventsService_RespondToInvitation_FullMethodName = "/events.v1.EventsService/RespondToInvitation"
	EventsService_CreatePost_FullMethodName          = "/events.v1.EventsService/CreatePost"
	EventsService_GetPosts_FullMethodName            = "/events.v1.EventsService/GetPosts"
	EventsService_DeletePost_FullMethodName          = "/events.v1.EventsService/DeletePost"
	EventsService_ReactToPost_FullMethodName         = "/events.v1.EventsService/ReactToPost"
	EventsService_GetAttendees_FullMethodName        = "/events.v1.EventsService/GetAttendees"
	EventsService_AddCoHost_FullMethodName           = "/events.v1.EventsService/AddCoHost"
	EventsService_RemoveCoHost_FullMethodName        = "/events.v1.EventsService/RemoveCoHost"
	EventsService_GetCategories_FullMethodName       = "/events.v1.EventsService/GetCategories"
	EventsService_SearchEvents_FullMethodName        = "/events.v1.EventsService/SearchEvents"
	EventsService_ShareEvent_FullMethodName          = "/events.v1.EventsService/ShareEvent"
	EventsService_GetNearbyEvents_FullMethodName     = "/events.v1.EventsService/GetNearbyEvents"
	EventsService_GetRecommendations_FullMethodName  = "/events.v1.EventsService/GetRecommendations"
	EventsService_GetTrending_FullMethodName         = "/events.v1.EventsService/GetTrending"
	EventsService_ReportRSVPEvent_FullMethodName     = "/events.v1.EventsService/ReportRSVPEvent"
)

// EventsServiceClient is the client API for EventsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventsServiceClient interface {
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*EventResponse, error)
	GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*EventResponse, error)
	UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*EventResponse, error)
	DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	GetMyEvents(ctx context.Context, in *GetMyEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	RSVP(ctx context.Context, in *RSVPRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetBirthdays(ctx context.Context, in *GetBirthdaysRequest, opts ...grpc.CallOption) (*BirthdaysResponse, error)
	InviteFriends(ctx context.Context, in *InviteFriendsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetInvitations(ctx context.Context, in *GetInvitationsRequest, opts ...grpc.CallOption) (*GetInvitationsResponse, error)
	RespondToInvitation(ctx context.Context, in *RespondToInvitationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*EventPost, error)
	GetPosts(ctx context.Context, in *GetPostsRequest, opts ...grpc.CallOption) (*GetPostsResponse, error)
	DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReactToPost(ctx context.Context, in *ReactToPostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAttendees(ctx context.Context, in *GetAttendeesRequest, opts ...grpc.CallOption) (*GetAttendeesResponse, error)
	AddCoHost(ctx context.Context, in *CoHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveCoHost(ctx context.Context, in *CoHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetCategories(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
	SearchEvents(ctx context.Context, in *SearchEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	ShareEvent(ctx context.Context, in *ShareEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetNearbyEvents(ctx context.Context, in *NearbyEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	GetRecommendations(ctx context.Context, in *RecommendationRequest, opts ...grpc.CallOption) (*RecommendationResponse, error)
	GetTrending(ctx context.Context, in *TrendingEventsRequest, opts ...grpc.CallOption) (*TrendingEventsResponse, error)
	ReportRSVPEvent(ctx context.Context, in *ReportRSVPEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type eventsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventsServiceClient(cc grpc.ClientConnInterface) EventsServiceClient {
	return &eventsServiceClient{cc}
}

func (c *eventsServiceClient) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, EventsService_CreateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, EventsService_GetEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, EventsService_UpdateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EventsService_DeleteEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, EventsService_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) GetMyEvents(ctx context.Context, in *GetMyEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, EventsService_GetMyEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) RSVP(ctx context.Context, in *RSVPRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EventsService_RSVP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) GetBirthdays(ctx context.Context, in *GetBirthdaysRequest, opts ...grpc.CallOption) (*BirthdaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BirthdaysResponse)
	err := c.cc.Invoke(ctx, EventsService_GetBirthdays_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) InviteFriends(ctx context.Context, in *InviteFriendsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EventsService_InviteFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) GetInvitations(ctx context.Context, in *GetInvitationsRequest, opts ...grpc.CallOption) (*GetInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInvitationsResponse)
	err := c.cc.Invoke(ctx, EventsService_GetInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) RespondToInvitation(ctx context.Context, in *RespondToInvitationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EventsService_RespondToInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*EventPost, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventPost)
	err := c.cc.Invoke(ctx, EventsService_CreatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) GetPosts(ctx context.Context, in *GetPostsRequest, opts ...grpc.CallOption) (*GetPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostsResponse)
	err := c.cc.Invoke(ctx, EventsService_GetPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EventsService_DeletePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) ReactToPost(ctx context.Context, in *ReactToPostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EventsService_ReactToPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) GetAttendees(ctx context.Context, in *GetAttendeesRequest, opts ...grpc.CallOption) (*GetAttendeesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttendeesResponse)
	err := c.cc.Invoke(ctx, EventsService_GetAttendees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) AddCoHost(ctx context.Context, in *CoHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EventsService_AddCoHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) RemoveCoHost(ctx context.Context, in *CoHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EventsService_RemoveCoHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) GetCategories(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, EventsService_GetCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) SearchEvents(ctx context.Context, in *SearchEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, EventsService_SearchEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) ShareEvent(ctx context.Context, in *ShareEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EventsService_ShareEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) GetNearbyEvents(ctx context.Context, in *NearbyEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, EventsService_GetNearbyEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) GetRecommendations(ctx context.Context, in *RecommendationRequest, opts ...grpc.CallOption) (*RecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendationResponse)
	err := c.cc.Invoke(ctx, EventsService_GetRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) GetTrending(ctx context.Context, in *TrendingEventsRequest, opts ...grpc.CallOption) (*TrendingEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrendingEventsResponse)
	err := c.cc.Invoke(ctx, EventsService_GetTrending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) ReportRSVPEvent(ctx context.Context, in *ReportRSVPEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EventsService_ReportRSVPEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventsServiceServer is the server API for EventsService service.
// All implementations must embed UnimplementedEventsServiceServer
// for forward compatibility.
type EventsServiceServer interface {
	CreateEvent(context.Context, *CreateEventRequest) (*EventResponse, error)
	GetEvent(context.Context, *GetEventRequest) (*EventResponse, error)
	UpdateEvent(context.Context, *UpdateEventRequest) (*EventResponse, error)
	DeleteEvent(context.Context, *DeleteEventRequest) (*emptypb.Empty, error)
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	GetMyEvents(context.Context, *GetMyEventsRequest) (*ListEventsResponse, error)
	RSVP(context.Context, *RSVPRequest) (*emptypb.Empty, error)
	GetBirthdays(context.Context, *GetBirthdaysRequest) (*BirthdaysResponse, error)
	InviteFriends(context.Context, *InviteFriendsRequest) (*emptypb.Empty, error)
	GetInvitations(context.Context, *GetInvitationsRequest) (*GetInvitationsResponse, error)
	RespondToInvitation(context.Context, *RespondToInvitationRequest) (*emptypb.Empty, error)
	CreatePost(context.Context, *CreatePostRequest) (*EventPost, error)
	GetPosts(context.Context, *GetPostsRequest) (*GetPostsResponse, error)
	DeletePost(context.Context, *DeletePostRequest) (*emptypb.Empty, error)
	ReactToPost(context.Context, *ReactToPostRequest) (*emptypb.Empty, error)
	GetAttendees(context.Context, *GetAttendeesRequest) (*GetAttendeesResponse, error)
	AddCoHost(context.Context, *CoHostRequest) (*emptypb.Empty, error)
	RemoveCoHost(context.Context, *CoHostRequest) (*emptypb.Empty, error)
	GetCategories(context.Context, *emptypb.Empty) (*GetCategoriesResponse, error)
	SearchEvents(context.Context, *SearchEventsRequest) (*ListEventsResponse, error)
	ShareEvent(context.Context, *ShareEventRequest) (*emptypb.Empty, error)
	GetNearbyEvents(context.Context, *NearbyEventsRequest) (*ListEventsResponse, error)
	GetRecommendations(context.Context, *RecommendationRequest) (*RecommendationResponse, error)
	GetTrending(context.Context, *TrendingEventsRequest) (*TrendingEventsResponse, error)
	ReportRSVPEvent(context.Context, *ReportRSVPEventRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedEventsServiceServer()
}

// UnimplementedEventsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventsServiceServer struct{}

func (UnimplementedEventsServiceServer) CreateEvent(context.Context, *CreateEventRequest) (*EventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEvent not implemented")
}
func (UnimplementedEventsServiceServer) GetEvent(context.Context, *GetEventRequest) (*EventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedEventsServiceServer) UpdateEvent(context.Context, *UpdateEventRequest) (*EventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (UnimplementedEventsServiceServer) DeleteEvent(context.Context, *DeleteEventRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (UnimplementedEventsServiceServer) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedEventsServiceServer) GetMyEvents(context.Context, *GetMyEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyEvents not implemented")
}
func (UnimplementedEventsServiceServer) RSVP(context.Context, *RSVPRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RSVP not implemented")
}
func (UnimplementedEventsServiceServer) GetBirthdays(context.Context, *GetBirthdaysRequest) (*BirthdaysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBirthdays not implemented")
}
func (UnimplementedEventsServiceServer) InviteFriends(context.Context, *InviteFriendsRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteFriends not implemented")
}
func (UnimplementedEventsServiceServer) GetInvitations(context.Context, *GetInvitationsRequest) (*GetInvitationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInvitations not implemented")
}
func (UnimplementedEventsServiceServer) RespondToInvitation(context.Context, *RespondToInvitationRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondToInvitation not implemented")
}
func (UnimplementedEventsServiceServer) CreatePost(context.Context, *CreatePostRequest) (*EventPost, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePost not implemented")
}
func (UnimplementedEventsServiceServer) GetPosts(context.Context, *GetPostsRequest) (*GetPostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPosts not implemented")
}
func (UnimplementedEventsServiceServer) DeletePost(context.Context, *DeletePostRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePost not implemented")
}
func (UnimplementedEventsServiceServer) ReactToPost(context.Context, *ReactToPostRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReactToPost not implemented")
}
func (UnimplementedEventsServiceServer) GetAttendees(context.Context, *GetAttendeesRequest) (*GetAttendeesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttendees not implemented")
}
func (UnimplementedEventsServiceServer) AddCoHost(context.Context, *CoHostRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCoHost not implemented")
}
func (UnimplementedEventsServiceServer) RemoveCoHost(context.Context, *CoHostRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveCoHost not implemented")
}
func (UnimplementedEventsServiceServer) GetCategories(context.Context, *emptypb.Empty) (*GetCategoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategories not implemented")
}
func (UnimplementedEventsServiceServer) SearchEvents(context.Context, *SearchEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchEvents not implemented")
}
func (UnimplementedEventsServiceServer) ShareEvent(context.Context, *ShareEventRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ShareEvent not implemented")
}
func (UnimplementedEventsServiceServer) GetNearbyEvents(context.Context, *NearbyEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNearbyEvents not implemented")
}
func (UnimplementedEventsServiceServer) GetRecommendations(context.Context, *RecommendationRequest) (*RecommendationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecommendations not implemented")
}
func (UnimplementedEventsServiceServer) GetTrending(context.Context, *TrendingEventsRequest) (*TrendingEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrending not implemented")
}
func (UnimplementedEventsServiceServer) ReportRSVPEvent(context.Context, *ReportRSVPEventRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportRSVPEvent not implemented")
}
func (UnimplementedEventsServiceServer) mustEmbedUnimplementedEventsServiceServer() {}
func (UnimplementedEventsServiceServer) testEmbeddedByValue()                       {}

// UnsafeEventsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventsServiceServer will
// result in compilation errors.
type UnsafeEventsServiceServer interface {
	mustEmbedUnimplementedEventsServiceServer()
}

func RegisterEventsServiceServer(s grpc.ServiceRegistrar, srv EventsServiceServer) {
	// If the following call panics, it indicates UnimplementedEventsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventsService_ServiceDesc, srv)
}

func _EventsService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_CreateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).CreateEvent(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetEvent(ctx, req.(*GetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_UpdateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).UpdateEvent(ctx, req.(*UpdateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_DeleteEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).DeleteEvent(ctx, req.(*DeleteEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_GetMyEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetMyEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetMyEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetMyEvents(ctx, req.(*GetMyEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_RSVP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSVPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).RSVP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_RSVP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).RSVP(ctx, req.(*RSVPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_GetBirthdays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBirthdaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetBirthdays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetBirthdays_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetBirthdays(ctx, req.(*GetBirthdaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_InviteFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).InviteFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_InviteFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).InviteFriends(ctx, req.(*InviteFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_GetInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetInvitations(ctx, req.(*GetInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_RespondToInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RespondToInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).RespondToInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_RespondToInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).RespondToInvitation(ctx, req.(*RespondToInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_CreatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_GetPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetPosts(ctx, req.(*GetPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_DeletePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).DeletePost(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_ReactToPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactToPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).ReactToPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_ReactToPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).ReactToPost(ctx, req.(*ReactToPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_GetAttendees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttendeesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetAttendees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetAttendees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetAttendees(ctx, req.(*GetAttendeesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_AddCoHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).AddCoHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_AddCoHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).AddCoHost(ctx, req.(*CoHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_RemoveCoHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).RemoveCoHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_RemoveCoHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).RemoveCoHost(ctx, req.(*CoHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetCategories(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_SearchEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).SearchEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_SearchEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).SearchEvents(ctx, req.(*SearchEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_ShareEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).ShareEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_ShareEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).ShareEvent(ctx, req.(*ShareEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_GetNearbyEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NearbyEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetNearbyEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetNearbyEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetNearbyEvents(ctx, req.(*NearbyEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetRecommendations(ctx, req.(*RecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_GetTrending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrendingEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetTrending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetTrending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetTrending(ctx, req.(*TrendingEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_ReportRSVPEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRSVPEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).ReportRSVPEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_ReportRSVPEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).ReportRSVPEvent(ctx, req.(*ReportRSVPEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventsService_ServiceDesc is the grpc.ServiceDesc for EventsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "events.v1.EventsService",
	HandlerType: (*EventsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _EventsService_CreateEvent_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _EventsService_GetEvent_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _EventsService_UpdateEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _EventsService_DeleteEvent_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _EventsService_ListEvents_Handler,
		},
		{
			MethodName: "GetMyEvents",
			Handler:    _EventsService_GetMyEvents_Handler,
		},
		{
			MethodName: "RSVP",
			Handler:    _EventsService_RSVP_Handler,
		},
		{
			MethodName: "GetBirthdays",
			Handler:    _EventsService_GetBirthdays_Handler,
		},
		{
			MethodName: "InviteFriends",
			Handler:    _EventsService_InviteFriends_Handler,
		},
		{
			MethodName: "GetInvitations",
			Handler:    _EventsService_GetInvitations_Handler,
		},
		{
			MethodName: "RespondToInvitation",
			Handler:    _EventsService_RespondToInvitation_Handler,
		},
		{
			MethodName: "CreatePost",
			Handler:    _EventsService_CreatePost_Handler,
		},
		{
			MethodName: "GetPosts",
			Handler:    _EventsService_GetPosts_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _EventsService_DeletePost_Handler,
		},
		{
			MethodName: "ReactToPost",
			Handler:    _EventsService_ReactToPost_Handler,
		},
		{
			MethodName: "GetAttendees",
			Handler:    _EventsService_GetAttendees_Handler,
		},
		{
			MethodName: "AddCoHost",
			Handler:    _EventsService_AddCoHost_Handler,
		},
		{
			MethodName: "RemoveCoHost",
			Handler:    _EventsService_RemoveCoHost_Handler,
		},
		{
			MethodName: "GetCategories",
			Handler:    _EventsService_GetCategories_Handler,
		},
		{
			MethodName: "SearchEvents",
			Handler:    _EventsService_SearchEvents_Handler,
		},
		{
			MethodName: "ShareEvent",
			Handler:    _EventsService_ShareEvent_Handler,
		},
		{
			MethodName: "GetNearbyEvents",
			Handler:    _EventsService_GetNearbyEvents_Handler,
		},
		{
			MethodName: "GetRecommendations",
			Handler:    _EventsService_GetRecommendations_Handler,
		},
		{
			MethodName: "GetTrending",
			Handler:    _EventsService_GetTrending_Handler,
		},
		{
			MethodName: "ReportRSVPEvent",
			Handler:    _EventsService_ReportRSVPEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "events/v1/events.proto",
}
