name: CI/CD Pipeline

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
    - name: Run tests
      run: |
        go test -v -race ./...
        go vet ./...
        staticcheck ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t messaging-app:latest .
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Push Docker image
      run: |
        docker tag messaging-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/messaging-app:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/messaging-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install kubectl
      uses: azure/setup-kubectl@v1
    - name: Deploy to Kubernetes
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        ./scripts/deploy.sh